JenkinsFile changed

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,74 +1,76 @@
-pipeline { 
+pipeline {
+ 
+    agent any
+ 
+    stages {
+ 
+        stage('Verify Application Files') {
 
-    agent any 
-
-    stages { 
-        stage('Checkout Source Code') {
             steps {
-                echo 'Downloading latest application code from GitHub...'
-                git branch: 'main',
-                url: 'https://github.com/Mangi09/jenkins-ci-demo.git'
+
+                echo 'Verifying project files...'
+ 
+                bat 'if exist index.html (echo index.html Found) else (exit 1)'
+
+                bat 'if exist style.css (echo style.css Found) else (exit 1)'
+
+                bat 'if exist script.js (echo script.js Found) else (exit 1)'
+
             }
+
         }
-        stage('Verify Application Files') { 
-
-            steps { 
-
-                echo 'Verifying project files...' 
-
  
+        stage('Checkout Source Code') {
 
-                bat 'if exist index.html (echo index.html Found) else (exit 1)' 
+            steps {
 
-                bat 'if exist style.css (echo style.css Found) else (exit 1)' 
+                echo 'Downloading latest application code from GitHub...'
 
+                git branch: 'main', url: 'https://github.com/Mangi09/jenkins-ci-demo.git'
 
-            } 
+            }
 
-        } 
-
-        stage('Create Build Artifact') { 
-
-            steps { 
-
-                echo 'Creating ZIP file...' 
-
-     bat 'powershell Compress-Archive -Path * -DestinationPath  
-
-StudentManagementSystem.zip -Force' 
-
-            } 
-
-        } 
-
-        stage('Archive Build') { 
-
-            steps { 
-
-                archiveArtifacts artifacts: 'VegetableWebsiteSystem.zip', fingerprint: true 
-
-            } 
-
-        } 
-
-    } 
-
+        }
  
+        stage('Create Build Artifact') {
 
-    post { 
+            steps {
 
-        success { 
+                echo 'Creating ZIP file...'
 
-            echo 'Application Build Successful.' 
+                bat 'powershell Compress-Archive -Path * -DestinationPath StudentManagementSystem.zip -Force'
 
-        } 
+            }
 
-        failure { 
+        }
+ 
+        stage('Archive Build') {
 
-            echo 'Application Build Failed.' 
+            steps {
 
-        } 
+                archiveArtifacts artifacts: 'StudentManagementSystem.zip', fingerprint: true
 
-    } 
+            }
+
+        }
+
+    }
+ 
+    post {
+
+        success {
+
+            echo 'Application Build Successful.'
+
+        }
+ 
+        failure {
+
+            echo 'Application Build Failed.'
+
+        }
+
+    }
 
 }
+ 
